# Generated by Django 4.2.2 on 2025-09-07 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acervo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagem',
            old_name='descricao',
            new_name='descricao_img',
        ),
        migrations.RenameField(
            model_name='imagem',
            old_name='titulo',
            new_name='titulo_img',
        ),
        migrations.AddField(
            model_name='imagem',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imagem',
            name='enviado_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='autor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='imagem',
            field=models.ImageField(upload_to='acervo/acervoimg/'),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('descricao_link', models.TextField()),
                ('titulo_link', models.CharField(max_length=200)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('autor', models.CharField(blank=True, max_length=100)),
                ('aprovado', models.BooleanField(default=False)),
                ('enviado_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Artigos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_artigo', models.CharField(max_length=200)),
                ('descricao_artigo', models.TextField()),
                ('arquivo', models.FileField(upload_to='acervo/artigos/')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('autor', models.CharField(blank=True, max_length=100)),
                ('aprovado', models.BooleanField(default=False)),
                ('enviado_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
