# Generated by Django 4.2.2 on 2025-11-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigos',
            name='discussao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagem',
            name='discussao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='discussao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videos',
            name='discussao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
