# Generated by Django 4.2.2 on 2025-11-14 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0002_artigos_discussao_imagem_discussao_link_discussao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_audio', models.CharField(max_length=200)),
                ('descricao_audio', models.TextField()),
                ('audio', models.FileField(upload_to='acervo/audios/')),
                ('discussao', models.TextField(blank=True, null=True)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('autor_audio', models.CharField(blank=True, max_length=100, null=True)),
                ('aprovado', models.CharField(choices=[('P', 'Pendente'), ('A', 'Aprovado'), ('R', 'Rejeitado')], default='P', max_length=1)),
                ('enviado_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
