# Generated by Django 4.2.2 on 2025-09-18 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0002_rename_descricao_imagem_descricao_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artigos',
            old_name='autor',
            new_name='autor_artigo',
        ),
        migrations.RenameField(
            model_name='imagem',
            old_name='autor',
            new_name='autor_img',
        ),
    ]
