# Generated by Django 4.2.2 on 2025-10-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0003_rename_autor_artigos_autor_artigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigos',
            name='aprovado',
            field=models.CharField(choices=[('P', 'Pendente'), ('A', 'Aprovado'), ('R', 'Rejeitado')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='aprovado',
            field=models.CharField(choices=[('P', 'Pendente'), ('A', 'Aprovado'), ('R', 'Rejeitado')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='link',
            name='aprovado',
            field=models.CharField(choices=[('P', 'Pendente'), ('A', 'Aprovado'), ('R', 'Rejeitado')], default='P', max_length=1),
        ),
    ]
