# Generated by Django 4.2.2 on 2025-10-08 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acervo', '0004_alter_artigos_aprovado_alter_imagem_aprovado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_video', models.CharField(max_length=200)),
                ('descricao_video', models.TextField()),
                ('video', models.FileField(upload_to='acervo/videos/')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('autor_video', models.CharField(blank=True, max_length=100)),
                ('aprovado', models.CharField(choices=[('P', 'Pendente'), ('A', 'Aprovado'), ('R', 'Rejeitado')], default='P', max_length=1)),
                ('enviado_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
