# Generated by Django 4.2.2 on 2025-10-13 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0005_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='autor_video',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
