# Generated by Django 4.2.2 on 2025-10-14 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0006_alter_videos_autor_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='autor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
