# Generated by Django 4.2.2 on 2025-11-05 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acervo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('artigo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='acervo.artigos')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('imagem', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='acervo.imagem')),
                ('link', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='acervo.link')),
                ('videos', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='acervo.videos')),
            ],
            options={
                'ordering': ['criado'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coment', models.TextField()),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.comentario')),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.topico')),
            ],
            options={
                'ordering': ['criado'],
            },
        ),
    ]
