# Generated by Django 4.2.2 on 2025-11-17 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topico',
            name='discussao',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
