# Generated by Django 4.2.2 on 2025-11-23 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0003_audio'),
        ('forum', '0003_topico_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topico',
            name='like',
        ),
        migrations.AddField(
            model_name='topico',
            name='audio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='acervo.audio'),
        ),
    ]
