# Generated by Django 4.2.2 on 2025-11-28 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_topico_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topico',
            name='like',
        ),
    ]
