# Generated by Django 4.2.2 on 2025-11-24 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_remove_topico_like_topico_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='topico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='forum.topico'),
        ),
    ]
