# Generated by Django 4.2.2 on 2025-11-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_alter_comentario_topico'),
    ]

    operations = [
        migrations.AddField(
            model_name='topico',
            name='autor_nome',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='topico',
            name='descricao',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
