# Generated by Django 4.2.2 on 2025-11-28 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0006_topico_autor_nome_topico_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topico',
            name='autor_nome',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='topico',
            name='descricao',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.CreateModel(
            name='Reagir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('like', 'Like'), ('deslike', 'Deslike')], max_length=7)),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacoes', to='forum.topico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('topico', 'usuario')},
            },
        ),
    ]
