# Generated by Django 4.2.2 on 2025-11-30 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_alter_topico_autor_nome_alter_topico_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='forum.comentario'),
        ),
    ]
